# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Edit < Formula
  desc "Edit directly a file on Amazon S3 in CLI"
  homepage "https://github.com/tsub/s3-edit"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsub/s3-edit/releases/download/v0.0.14/s3-edit_0.0.14_darwin_amd64.tar.gz"
      sha256 "635ae03d349fa61b0fd2f5835e0f8cc25d9ad68a56eff29a7dfc39f4c9e9cbed"

      def install
        bin.install 's3-edit'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsub/s3-edit/releases/download/v0.0.14/s3-edit_0.0.14_linux_arm64.tar.gz"
      sha256 "ebe1379ae7bb104bbe9eb639a4a16f6bd42bbfbe89a0c41905a87bd2c6840e72"

      def install
        bin.install 's3-edit'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tsub/s3-edit/releases/download/v0.0.14/s3-edit_0.0.14_linux_amd64.tar.gz"
      sha256 "426b845d1d717bb76dc4a4de816353039e76dfcbcdc478d15dacf8f41162c36d"

      def install
        bin.install 's3-edit'
      end
    end
  end
end
